### ISSUE TITLE
About the save_jpg function

### ISSUE THREAD

**Issue by songyonger** [boazarad/NTIRE2022_spectral#1]
About this line: ’rgb *=(TYPICAL_SCENE_REFLECTIVITY / rgb.mean()) * MAX_VAL_8_BIT‘ , I want to know what the TYPICAL_SCENE_REFLECTIVITY means and why divide rgb.mean(). And this way changes the original rgb’s brightness, so will it increase the difficulty to reconstruct a hyperspectral image? I have tested some SOTA models on this dataset but get a high MRAE.

**Comment by boazarad** [comment]
Hi songyonger,
This is indeed by design, as it is a similar process to what might occur in a physical RGB camera:
Exposure is set in a way that most of the scene will be within the cameras dynamic range (in this case we assume a very simple average illuminance approach to exposure setting). This means that pixels which are significantly brighter than the scene average might be "clipped" in one or all color channels.

TYPICAL_SCENE_REFLECTIVITY is the desired average brightness of the image (consider this the exposure setting) and the calculation you quoted brings the image average to TYPICAL_SCENE_REFLECTIVITY and then discretizes to 8 bits.

Keep in mind that all input HS images are normalized, so if your method reconstructs spectra correctly, you should be able to tune the "brightness" of the spectral image based on this prior knowledge.

Also see:
Lin, Yi-tun and Finlayson, Graham D. (2019) Exposure Invariance in Spectral Reconstruction from RGB Images
(https://ueaeprints.uea.ac.uk/id/eprint/73362/)
Which may explain why many SOTA methods are quite sensitive to variable brightness.

**Comment by songyonger** [comment]
Thanks!
